name: flutter_face_api_example
description: Demonstrates how to use the flutter_face_api plugin.

publish_to: 'none'

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  path_provider: ^1.6.5
  image_picker: ^0.6.4
  flutter:
    sdk: flutter
  flutter_face_api:
    path: ../
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
  uses-material-design: true
