name: flutter_face_api_example
description: Demonstrates how to use the flutter_face_api plugin.

publish_to: 'none'

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  path_provider: ^2.0.11
  image_picker: ^0.8.6
  flutter:
    sdk: flutter
  flutter_face_api:
    path: ../
  flutter_face_core: 5.2.0
  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
  uses-material-design: true
